; PlatformIO configuration for ReactiveArduino library testing

[platformio]
; Define environments for different examples
;default_envs = distinct_example

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
build_src_filter = -<*>

[env:accelerometer]
build_src_filter = +<../examples/Accelerometer/>

[env:analog_input_update]
build_src_filter = +<../examples/AnalogInputUpdate/>

[env:blink]
build_src_filter = +<../examples/Blink/>

[env:distinct]
build_src_filter = +<../examples/Distinct/>

[env:do]
build_src_filter = +<../examples/Do/>

[env:from_array]
build_src_filter = +<../examples/FromArray/>

[env:from_property]
build_src_filter = +<../examples/FromProperty/>

[env:from_serial_port]
build_src_filter = +<../examples/FromSerialPort/>

[env:from_string]
build_src_filter = +<../examples/FromString/>

[env:global_defined]
build_src_filter = +<../examples/GlobalDefined/>

[env:pid_motor_speed_control]
build_src_filter = +<../examples/PIDMotorSpeedControl/>

[env:pid_temperature_control]
build_src_filter = +<../examples/PIDTemperatureControl/>

[env:reduce]
build_src_filter = +<../examples/Reduce/>

[env:rotary_encoder]
build_src_filter = +<../examples/RotaryEncoder/>

[env:throttle]
build_src_filter = +<../examples/Throttle/>

[env:ultrasonic]
build_src_filter = +<../examples/Ultrasonic/>
